# Generated by Django 5.0.3 on 2024-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='anemometer_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='anemometer_data_cm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='gc_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='gc_power_cm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='mission_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='mission_choice_cm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='mission_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='windy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='windy_data_cm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='wp_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='wp_details_cm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='wp_heading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='wp_heading_cm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
