# Generated by Django 5.0.3 on 2024-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flightapp', '0002_flight_anemometer_data_flight_anemometer_data_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airspace_clearance',
            field=models.BooleanField(default=False),
        ),
    ]
